<a href="https://colab.research.google.com/github/BKousha/FloorPlanSegmentation/blob/main/Generate_images.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/My Drive"

Mounted at /content/drive
'Colab Notebooks'
'Copy of Predictive Maintenance Checklist.gdoc'
 FloorPlan_samples
 model_best_val_loss_var.pkl
 Processed_Floor_Plans
 ShotBot
'SNN_soft shadow network for image compositing.pdf'
 test.txt


In [ ]:
import os
import glob
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from tqdm import tqdm


# import tensorflow as tf
# from tensorflow import keras
# from tensorflow.keras import layers


# Step 1: Data Preparation


In [ ]:

def divide_image_into_patches(image_path, mask_path, patch_size, overlap,resize_size,color_mapping,save_image_folder,save_mask_folder):
    # Load the image and mask
    print(mask_path)
    image = cv2.imread(image_path)
    mask = cv2.imread(mask_path)

    print(mask)

    # Determine the dimensions of the image and calculate the number of patches
    height, width = image.shape[:2]
    stride = patch_size - overlap
    num_rows = (height - patch_size) // stride + 1
    num_cols = (width - patch_size) // stride + 1

    print('num_rows:',num_rows)
    print('num_cols:',num_cols)

    # Divide the image and mask into patches
    image_patches = []
    mask_patches = []
    for i in range(num_rows):
        for j in range(num_cols):
            start_x = i * stride
            start_y = j * stride
            end_x = start_x + patch_size
            end_y = start_y + patch_size

            image_patch = image[start_x:end_x, start_y:end_y]
            mask_patch = mask[start_x:end_x, start_y:end_y]
            print('mask_patch size before:',mask_patch.shape)

            image_patch = cv2.resize(image_patch, resize_size)
            mask_patch  = cv2.resize(mask_patch,  resize_size)
            print('mask_patch size after:',mask_patch.shape)

            #mask_patch = preprocess_mask(mask_patch, color_mapping)
            #print('mask_patch size after processed:',mask_patch.shape)

            save_image_path = os.path.join(save_image_folder, f'image_{i}.png')
            cv2.imwrite(save_image_path, image_patch)

            # Save processed mask
            save_mask_path = os.path.join(save_mask_folder, f'mask_{i}.png')
            cv2.imwrite(save_mask_path, mask_patch)

            image_patches.append(image_patch)
            mask_patches.append(mask_patch)

    return image_patches, mask_patches

def generate_data(image_folder, mask_folder, patch_size, overlap,resize_size, color_mapping, save_image_folder, save_mask_folder):
    image_files = glob.glob(os.path.join(image_folder, '*.png'))
    print('Number of images:', len(image_files))

    os.makedirs(save_image_folder, exist_ok=True)
    os.makedirs(save_mask_folder, exist_ok=True)

    with tqdm(total=len(image_files), desc='Processing Images') as pbar:
        for image_file in image_files:
            mask_file = os.path.join(mask_folder, os.path.basename(image_file))
            image_patches, mask_patches = divide_image_into_patches(image_file, mask_file, patch_size, overlap, resize_size,color_mapping,save_image_folder,save_mask_folder)

            pbar.update(1)



# Step 3: Read the data


In [ ]:


image_folder = '/content/drive/MyDrive/Processed_Floor_Plans/FP_raw'
mask_folder = '/content/drive/MyDrive/Processed_Floor_Plans/FP_processed'

save_image_folder = '/content/drive/MyDrive/FloorPlan_samples/smaller images/temp_images'
save_mask_folder = '/content/drive/MyDrive/FloorPlan_samples/smaller images/temp_masks'

resize_size = (512, 512)

patch_size = 1024
input_shape = (patch_size, patch_size, 3)

overlap = 50


generate_data(image_folder, mask_folder, patch_size, overlap, resize_size, color_mapping, save_image_folder, save_mask_folder)


Number of images: 302


Processing Images:   0%|          | 0/302 [00:00<?, ?it/s]

/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/41.png
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
num_rows: 1
num_cols: 1
mask_patch size before: (4096, 4096, 3)
mask_patch size after: (512, 512, 3)


Processing Images:   0%|          | 1/302 [00:03<18:08,  3.62s/it]

/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/42.png


Processing Images:   1%|          | 2/302 [00:05<13:53,  2.78s/it]

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
num_rows: 0
num_cols: 1
/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/43.png


Processing Images:   1%|          | 3/302 [00:08<13:21,  2.68s/it]

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
num_rows: 0
num_cols: 0
/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/44.png


Processing Images:   1%|▏         | 4/302 [00:12<15:28,  3.11s/it]

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
num_rows: 0
num_cols: 0
/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/45.png


Processing Images:   2%|▏         | 5/302 [00:13<12:39,  2.56s/it]

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
num_rows: 0
num_cols: 0
/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/46.png


Processing Images:   2%|▏         | 6/302 [00:14<09:41,  1.96s/it]

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [227 219 129]
  [227 219 129]
  [227 219 129]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
num_rows: 0
num_cols: 0
/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/47.png


Processing Images:   2%|▏         | 7/302 [00:15<07:52,  1.60s/it]

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
num_rows: 0
num_cols: 0
/content/drive/MyDrive/Processed_Floor_Plans/FP_processed/48.png


Processing Images:   2%|▏         | 7/302 [00:16<11:26,  2.33s/it]


KeyboardInterrupt: ignored

In [ ]:
image_2d = mask.reshape(-1, 3)
image_2d
unique_colors =np.unique(image_2d, axis=0)
print(len(unique_colors))
unique_colors

278


array([[ 57,  52, 251],
       [ 57,  57, 245],
       [ 59,  53, 245],
       [ 62,  51, 245],
       [ 70, 247,  22],
       [ 74,  71, 194],
       [128,  73,  48],
       [129, 218, 226],
       [129, 219, 227],
       [130, 217, 225],
       [130, 218, 226],
       [131, 215, 223],
       [131, 216, 224],
       [132, 214, 222],
       [132, 215, 223],
       [133, 212, 221],
       [133, 213, 221],
       [134, 210, 218],
       [134, 211, 219],
       [134, 212, 220],
       [135, 209, 217],
       [135, 209, 218],
       [136, 207, 216],
       [136, 208, 216],
       [137, 206, 214],
       [137, 206, 215],
       [138, 204, 212],
       [138, 204, 213],
       [138, 205, 214],
       [139, 202, 211],
       [139, 203, 211],
       [140, 201, 209],
       [140, 201, 210],
       [141, 199, 208],
       [141, 200, 209],
       [142, 198, 206],
       [142, 198, 207],
       [143, 195, 204],
       [143, 196, 205],
       [143, 197, 206],
       [144, 194, 203],
       [144, 195

In [ ]:
np.unique(label_map.flatten()/8)

array([0.   , 0.125, 0.25 , 0.375, 0.625, 0.75 , 1.   ])

In [ ]:

height, width, _ = mask.shape
label_map = np.zeros((height, width), dtype=np.uint8)
print('preprocess_mask')
#print(mask)
k=0
for i in range(height):
    for j in range(width):
        rgb = tuple(mask[i, j])
        if rgb in color_mapping:
            label_map[i, j] = color_mapping[rgb]
            k+=1

print(k)

preprocess_mask


In [ ]:
import numpy as np

# Define the color mapping dictionary
color_mapping = {
    (244, 31, 46): 1,    # rooms
    (246, 77, 89): 1,    # rooms (alternative RGB definition)
    (70, 247, 22): 2,    # hallway
    (248, 172, 98): 3,   # kitchen
    (182, 112, 80): 3,   # kitchen (alternative RGB definition)
    (244, 190, 96): 3,   # kitchen (alternative RGB definition)
    (252, 226, 49): 4,   # columns
    (182, 11, 80): 5,    # mep
    (116, 53, 54): 5,    # mep
    (136, 208, 216): 6,  # windows
    (129, 219, 227): 6,  # windows
    (131, 217, 225): 6,  # windows
    (57, 52, 251): 7,    # doors
    (42, 75, 97): 7,     # doors
    (97, 97, 110): 7,    # doors
    (207, 81, 216): 8,   # glass_doors
    (223, 79, 165): 8,   # glass_doors
    (153, 109, 89): 9,   # bathrooms
    (128, 73, 48): 9,    # bathrooms
    (214, 194, 223): 10, # elevators
    (199, 184, 185): 10, # elevators (alternative RGB definition)
    (166, 162, 160): 11, # stairs
    (197, 141, 115): 12, # storage
    (193, 113, 77): 12,  # storage
    (105, 104, 159): 13, # elevator_doors
}

# Define the RGB threshold value for color matching
threshold = 10

# Load your image into a numpy array (assuming it's already stored)

# Create an empty 2D array to store the translated values
translated_array = np.zeros(mask.shape[:2], dtype=np.uint8)

# Iterate over each pixel in the image
for i in range(mask.shape[0]):
    for j in range(mask.shape[1]):
        pixel = mask[i, j]

        # Find the matching color in the color mapping dictionary
        matching_color = 0
        for color, value in color_mapping.items():
            if all(abs(pixel - np.array(color)) <= threshold):
                matching_color = value
                break

        # Assign the matching value to the corresponding position in the translated array
        translated_array[i, j] = matching_color

# The translated_array now contains the corresponding identifiers for each object

# Perform further operations using the translated_array as needed


image_2d = translated_array.reshape(-1, 3)
image_2d
unique_colors =np.unique(image_2d, axis=0)
print(len(unique_colors))


KeyboardInterrupt: ignored

# Step 2: Dataset Creation


In [ ]:

def preprocess_input(image, mask):
    image = image.astype(np.float32) / 255.0
    mask = tf.keras.utils.to_categorical(mask, num_classes=25)
    return image, mask

def create_dataset(data, batch_size, shuffle=True):
    images, masks = zip(*data)
    images = np.array(images)
    masks = np.array(masks)

    dataset = tf.data.Dataset.from_tensor_slices((images, masks))
    dataset = dataset.map(preprocess_input)
    if shuffle:
        dataset = dataset.shuffle(buffer_size=len(data))
    dataset = dataset.batch(batch_size)

    return dataset


image_files = sorted(glob.glob(os.path.join(save_image_folder, '*.png')))
mask_files = sorted(glob.glob(os.path.join(save_mask_folder, '*.png')))

dataset = tf.data.Dataset.from_tensor_slices((image_files, mask_files))

Number of images: 300


KeyboardInterrupt: ignored

In [ ]:
def plot_images_with_masks(images, masks, color_mapping):
    num_images = len(images)

    fig, axs = plt.subplots(num_images, 2, figsize=(10, 10*num_images))

    for i in range(num_images):
        image = images[i]
        mask = masks[i]

        axs[i, 0].imshow(image)
        axs[i, 0].axis('off')
        axs[i, 0].set_title('Input Image')

        axs[i, 1].imshow(mask, cmap='viridis', vmin=0, vmax=len(color_mapping)-1)
        axs[i, 1].axis('off')
        axs[i, 1].set_title('Mask')

    plt.tight_layout()
    plt.show()

# Display example images and masks
example_images = [data[i][0] for i in range(5)]
example_masks = [data[i][1] for i in range(5)]

plot_images_with_masks(example_images, example_masks, color_mapping)

# Step 4: Model Definition


In [ ]:

def unet_model(input_shape, num_classes):
    inputs = keras.Input(shape=input_shape)

    # Encoder
    conv1 = layers.Conv2D(64, 3, activation='relu', padding='same')(inputs)
    # ...

    # Decoder
    upconv1 = layers.Conv2DTranspose(64, 2, strides=2, padding='same')(conv9)
    # ...

    outputs = layers.Conv2D(num_classes, 1, activation='softmax')(upconv1)
    model = keras.Model(inputs, outputs)
    return model

# Step 4: Training

In [ ]:
model = unet_model(input_shape, num_classes)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(dataset, epochs=10)

# Step 5: Evaluation
# Evaluate the model on the test set or perform any other desired evaluation steps
